-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cliente
(
    piva character varying(11) COLLATE pg_catalog."default" NOT NULL,
    nome character varying COLLATE pg_catalog."default",
    cognome character varying COLLATE pg_catalog."default",
    mail character varying COLLATE pg_catalog."default",
    via character varying COLLATE pg_catalog."default",
    citta character varying COLLATE pg_catalog."default",
    civico character varying COLLATE pg_catalog."default",
    cap character varying COLLATE pg_catalog."default",
    CONSTRAINT cliente_pkey PRIMARY KEY (piva)
);

CREATE TABLE IF NOT EXISTS public.credenziali_cliente
(
    cliente_piva character varying(11) COLLATE pg_catalog."default" NOT NULL,
    cliente_mail character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cliente_password character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT credenziali_cliente_pkey PRIMARY KEY (cliente_piva)
);

CREATE TABLE IF NOT EXISTS public.impiegato
(
    cod_impiegato character varying COLLATE pg_catalog."default" NOT NULL,
    nome character varying COLLATE pg_catalog."default",
    cognome character varying COLLATE pg_catalog."default",
    mail character varying COLLATE pg_catalog."default" NOT NULL,
    tipo boolean,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT impiegato_pkey PRIMARY KEY (cod_impiegato)
);

CREATE TABLE IF NOT EXISTS public.impiegato_magazzino
(
    cod_prodotto character varying COLLATE pg_catalog."default" NOT NULL,
    cod_impiegato character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT impiegato_magazzino_pkey PRIMARY KEY (cod_prodotto, cod_impiegato)
);

CREATE TABLE IF NOT EXISTS public.impiegato_serra
(
    cod_serra character varying COLLATE pg_catalog."default" NOT NULL,
    cod_impiegato character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT impiegato_serra_pkey PRIMARY KEY (cod_serra, cod_impiegato)
);

CREATE TABLE IF NOT EXISTS public.materie_magazzino
(
    cod_prodotto character varying COLLATE pg_catalog."default" NOT NULL,
    nome character varying COLLATE pg_catalog."default",
    quantita integer,
    CONSTRAINT materie_magazzino_pkey PRIMARY KEY (cod_prodotto)
);

CREATE TABLE IF NOT EXISTS public.ordine
(
    piva character varying COLLATE pg_catalog."default",
    data date,
    ora character varying COLLATE pg_catalog."default",
    costo_totale double precision,
    quantita integer,
    cod_specie character varying COLLATE pg_catalog."default",
    cod_ordine bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT ordine_pkey PRIMARY KEY (cod_ordine)
);

CREATE TABLE IF NOT EXISTS public.serra
(
    cod_serra character varying COLLATE pg_catalog."default" NOT NULL,
    capienza integer,
    CONSTRAINT serra_pkey PRIMARY KEY (cod_serra)
);

CREATE TABLE IF NOT EXISTS public.specie_piantina
(
    cod_specie character varying COLLATE pg_catalog."default" NOT NULL,
    nome character varying COLLATE pg_catalog."default",
    stagione character varying COLLATE pg_catalog."default",
    tempario character varying COLLATE pg_catalog."default",
    costo double precision,
    immagine character varying COLLATE pg_catalog."default",
    CONSTRAINT specie_piantina_pkey PRIMARY KEY (cod_specie)
);

ALTER TABLE IF EXISTS public.credenziali_cliente
    ADD CONSTRAINT cliente_piva FOREIGN KEY (cliente_piva)
    REFERENCES public.cliente (piva) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS credenziali_cliente_pkey
    ON public.credenziali_cliente(cliente_piva);


ALTER TABLE IF EXISTS public.impiegato_magazzino
    ADD CONSTRAINT cod_impiegato FOREIGN KEY (cod_impiegato)
    REFERENCES public.impiegato (cod_impiegato) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.impiegato_magazzino
    ADD CONSTRAINT cod_prodotto FOREIGN KEY (cod_prodotto)
    REFERENCES public.materie_magazzino (cod_prodotto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.impiegato_serra
    ADD CONSTRAINT cod_impiegato FOREIGN KEY (cod_impiegato)
    REFERENCES public.impiegato (cod_impiegato) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.impiegato_serra
    ADD CONSTRAINT cod_serra FOREIGN KEY (cod_serra)
    REFERENCES public.serra (cod_serra) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;